CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Enable Floating Point values
CONFIG_CBPRINTF_FP_SUPPORT=y

# Peripheral Support
CONFIG_SPI=y
CONFIG_SENSOR=y
CONFIG_ADXL367=y
CONFIG_ADXL367_TRIGGER_OWN_THREAD=y
CONFIG_BMP585=y
CONFIG_BMP585_TRIGGER=y

# Increase stack size for the main thread and System Workqueue
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048

# Used for debugging SPI issues only
# CONFIG_SPI_LOG_LEVEL_DBG=y

# Enable the Shell subsystem
CONFIG_SHELL=y
CONFIG_SHELL_LOG_BACKEND=y

# Enable UART backend for the shell
CONFIG_SHELL_BACKEND_SERIAL=y

# Optional: Set shell buffer sizes and history
CONFIG_SHELL_CMD_BUFF_SIZE=128
CONFIG_SHELL_HISTORY=y